In [2]:
import numpy as np

In [5]:
one_d = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
one_d.reshape(3,2,2)# three arguments signifies that array is 3-D 
# and 3X2X2 explains:three 2-d arrays w'd be created, having 2-rows n 2-colomns
#prc. different combinations of 3-D array which should total as 12

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [6]:
one_d.reshape(1,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

# Flatten Array

In [11]:
reshapped_one_d = one_d.reshape(1,3,4)
print(reshapped_one_d) 
#flatten the array using flatten() method
reshapped_one_d.flatten()

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
reshapped_one_d = one_d.reshape(1,3,4)
print(reshapped_one_d)
#flatten the array suing ravel() method
reshapped_ond_d2 = np.ravel(reshapped_one_d)
reshapped_ond_d2

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Broadcasting
  
  - Broadcastig is a powerfull feature of Numpy. it allows us perform operations on arrays with different shapes and sizes. for example one can add scalar to an array or multiply two arrays with different shapes. NumPy automatically broadcasts to the appropriate shape and performs the operation

In [17]:
ond_d = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
multiply5=one_d*5
print(multiply5)

[ 5 10 15 20 25 30 35 40 45 50 55 60]


In [18]:
add10=one_d+10
print(add10)

[11 12 13 14 15 16 17 18 19 20 21 22]


In [20]:
b = np.array([[1,2,3],[4,5,6]])
c = np.array([10,20,30])
#Numpy broadcasts the 1D array c to shape (2, 3) to match the shape of b and then adds two arrays element-wise
d = b + c
print(d)

[[11 22 33]
 [14 25 36]]
